[package]
name = "aliyun-oss-rust-sdk"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
thiserror = "1.0"
anyhow = "1.0"
once_cell = "1.7"

reqwest = "0.11"
md5 = "0.7"

[dev-dependencies]
pretty_env_logger = "0.4"

[dev-dependencies.tokio]
version = "1.0.3"
default-features = false
features = [ "rt", "rt-multi-thread", "net", "sync", "io-util", "macros", "time", "signal" ]
